[2025-04-05 12:52:49,553] WARN Session 0x10002e9cc270000 for server localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
EndOfStreamException: Unable to read additional data from server sessionid 0x10002e9cc270000, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
[2025-04-05 12:53:53,422] ERROR Error while reading checkpoint file /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/cleaner-offset-checkpoint (org.apache.kafka.storage.internals.log.LogDirFailureChannel)
java.nio.file.NoSuchFileException: /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/cleaner-offset-checkpoint
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:159)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2897)
	at org.apache.kafka.server.common.CheckpointFile.read(CheckpointFile.java:92)
	at org.apache.kafka.storage.internals.checkpoint.CheckpointFileWithFailureHandler.read(CheckpointFileWithFailureHandler.java:74)
	at kafka.server.checkpoints.OffsetCheckpointFile.read(OffsetCheckpointFile.scala:75)
	at kafka.log.LogCleanerManager.$anonfun$allCleanerCheckpoints$2(LogCleanerManager.scala:147)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.immutable.List$.from(List.scala:685)
	at scala.collection.immutable.List$.from(List.scala:682)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.flatMap(Iterable.scala:686)
	at scala.collection.IterableOps.flatMap$(Iterable.scala:686)
	at scala.collection.AbstractIterable.flatMap(Iterable.scala:935)
	at kafka.log.LogCleanerManager.$anonfun$allCleanerCheckpoints$1(LogCleanerManager.scala:145)
	at kafka.log.LogCleanerManager.allCleanerCheckpoints(LogCleanerManager.scala:153)
	at kafka.log.LogCleanerManager.$anonfun$grabFilthiestCompactedLog$1(LogCleanerManager.scala:184)
	at kafka.log.LogCleanerManager.grabFilthiestCompactedLog(LogCleanerManager.scala:181)
	at kafka.log.LogCleaner$CleanerThread.cleanFilthiestLog(LogCleaner.scala:405)
	at kafka.log.LogCleaner$CleanerThread.tryCleanFilthiestLog(LogCleaner.scala:392)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:378)
	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:135)
[2025-04-05 12:53:52,734] ERROR Error while writing to checkpoint file /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/log-start-offset-checkpoint (org.apache.kafka.storage.internals.log.LogDirFailureChannel)
java.io.FileNotFoundException: /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/log-start-offset-checkpoint.tmp (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
	at org.apache.kafka.server.common.CheckpointFile.write(CheckpointFile.java:78)
	at org.apache.kafka.storage.internals.checkpoint.CheckpointFileWithFailureHandler.write(CheckpointFileWithFailureHandler.java:52)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:71)
	at kafka.log.LogManager.$anonfun$checkpointLogStartOffsetsInDir$1(LogManager.scala:874)
	at kafka.log.LogManager.$anonfun$checkpointLogStartOffsetsInDir$1$adapted(LogManager.scala:869)
	at scala.Option.foreach(Option.scala:437)
	at kafka.log.LogManager.checkpointLogStartOffsetsInDir(LogManager.scala:869)
	at kafka.log.LogManager.$anonfun$checkpointLogStartOffsets$1(LogManager.scala:824)
	at kafka.log.LogManager.$anonfun$checkpointLogStartOffsets$1$adapted(LogManager.scala:823)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at kafka.log.LogManager.checkpointLogStartOffsets(LogManager.scala:823)
	at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$6(LogManager.scala:642)
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:150)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[2025-04-05 12:53:52,734] ERROR Error while writing to checkpoint file /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/recovery-point-offset-checkpoint (org.apache.kafka.storage.internals.log.LogDirFailureChannel)
java.io.FileNotFoundException: /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/recovery-point-offset-checkpoint.tmp (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:179)
	at org.apache.kafka.server.common.CheckpointFile.write(CheckpointFile.java:78)
	at org.apache.kafka.storage.internals.checkpoint.CheckpointFileWithFailureHandler.write(CheckpointFileWithFailureHandler.java:52)
	at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:71)
	at kafka.log.LogManager.$anonfun$checkpointRecoveryOffsetsInDir$1(LogManager.scala:850)
	at kafka.log.LogManager.$anonfun$checkpointRecoveryOffsetsInDir$1$adapted(LogManager.scala:846)
	at scala.Option.foreach(Option.scala:437)
	at kafka.log.LogManager.checkpointRecoveryOffsetsInDir(LogManager.scala:846)
	at kafka.log.LogManager.$anonfun$checkpointLogRecoveryOffsets$1(LogManager.scala:813)
	at kafka.log.LogManager.$anonfun$checkpointLogRecoveryOffsets$1$adapted(LogManager.scala:811)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at kafka.log.LogManager.checkpointLogRecoveryOffsets(LogManager.scala:811)
	at kafka.log.LogManager.$anonfun$startupWithConfigOverrides$5(LogManager.scala:638)
	at org.apache.kafka.server.util.KafkaScheduler.lambda$schedule$1(KafkaScheduler.java:150)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[2025-04-06 09:38:06,598] ERROR Disk error while writing log start offsets checkpoint in directory /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1: Error while writing to checkpoint file /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/log-start-offset-checkpoint (kafka.log.LogManager)
[2025-04-06 09:38:06,598] WARN [ReplicaManager broker=1] Stopping serving replicas in dir /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1 with uuid None because the log directory has failed. (kafka.server.ReplicaManager)
[2025-04-06 09:38:06,598] ERROR Disk error while writing recovery offsets checkpoint in directory /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1: Error while writing to checkpoint file /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1/recovery-point-offset-checkpoint (kafka.log.LogManager)
[2025-04-06 09:38:06,604] WARN [ReplicaManager broker=1] Broker 1 stopped fetcher for partitions  and stopped moving logs for partitions  because they are in the failed log directory /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1. (kafka.server.ReplicaManager)
[2025-04-06 09:38:06,607] WARN Stopping serving logs in dir /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1 (kafka.log.LogManager)
[2025-04-06 09:38:06,609] ERROR Shutdown broker because all log dirs in /Users/shubhamdixit/Downloads/kafka_2.13-3.8.1/tmp/kafka-logs-1 have failed (kafka.log.LogManager)
